name: Missing redirects check

on:
  push:

jobs:
  check_redirects:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for missing redirects
        run: |
          find docs -type f -name "*.md" | while read file; do
            frontmatter=$(cat $file | grep -Po 'redirect_from: *\K.*')
            relative_path="${file%.md}.md"
            if ! [[ $frontmatter =~ $relative_path ]]; then
              echo "Error: Missing redirect for $relative_path"
              exit 1
            fi
          done