name: Missing redirects check

on:
  push:

jobs:
  check_redirects:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for missing redirects
        run: |
          missing_redirects=""
          find docs -type f -name "*.md" -print0 | xargs -0 -I {} bash -c '
            file="$1"
            frontmatter=$(cat "$file" | grep -Po "redirect_from: *\K.*")
            relative_path="${file%.md}.md"
            if ! [[ $frontmatter =~ $relative_path ]]; then
              missing_redirects="$missing_redirects\nError: Missing redirect for $relative_path"
            fi
          ' -- {}

          if [ -n "$missing_redirects" ]; then
            echo -e "Workflow failed due to missing redirects:$missing_redirects"
            exit 1
          fi