name: Missing redirects check

on:
  push:

jobs:
  check_redirects:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for missing redirects
        run: |
          find docs -type f -name "*.md" | while read file; do
            relative_path="${file%.md}.md"
            if ! grep -q "${relative_path}" docs/*; then
              echo "Error: Missing redirect for $relative_path"
              exit 1
            fi
          done

      - name: Fail if missing redirects are found
        if: ${{ always() }}
        run: |
          if [ -s missing-redirects.txt ]; then
            echo "Workflow failed due to missing redirects"
            cat missing-redirects.txt
            exit 1
          fi